apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.pdb.name2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app1 }}
      version: {{ .Values.labels.version2 }}
