{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name2 }}
  labels:
    app: {{ .Values.labels.app1 }}
    version: {{ .Values.labels.version2 }}
   # {{- include "shop-reviews.labels" . | nindent 4 }}
  #{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}