apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # containerPort: {{ .Values.service.containerPort}}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    version2: {{ .Values.labels.version2 }}
    version: {{ .Values.labels.version }}
