apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # Base64-encoded 'postgres'
  password: YnJvb2s=       # Base64-encoded 'brook'
  database: bWFubmFycz0=  # Base64-encoded 'mannars'
